
[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = "dagrunner"
version = '0.1.0'
description = 'Execute a DAG.'
authors = [{name = "Mitchell Tillman", email ="mtillman14@gmail.com"}]
dependencies = [
    "dagpiler",
    "dataset-builder",
]

