
[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = "dagrunner"
version = '0.1.0'
description = 'A template for a Python project.'
authors = [{name = "Mitchell Tillman", email ="mtillman14@gmail.com"}]
dependencies = [

]

